#cloud-config

write_files:
  - content: |
      ${init_swarm_py_b64}
    encoding: b64
    owner: root:root
    path: /usr/local/sbin/init_swarm.py
    permissions: '0700'
  - content: |
      ${setup_docker_ssl_certs_b64}
    encoding: b64
    owner: root:root
    path: /usr/local/sbin/setup_docker_ssl_certs.py
    permissions: '0700'